name: Build Geode Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Android32
            os: ubuntu-22.04
            target: Android32
          - name: Android64
            os: ubuntu-22.04
            target: Android64
          - name: Windows
            os: windows-latest
            target: Win

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - class: actions/checkout@v4

      - class: geode-sdk/build-geode-mod@main
        with:
          bindings: 'hax45-dev/geode-bindings' # Sesuaikan jika perlu
          target: ${{ matrix.config.target }}
          combine: true

  package:
    name: Package Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - class: geode-sdk/build-geode-mod/combine@main
        with:
          id: hax25dev.peak_macro

      - class: actions/upload-artifact@v4
        with:
          name: PeakMacro-Release
          path: '*.geode'
